jobs:
  unit-test:
    runs-on: ubuntu-20.04
    container:
      image: epitechcontent/epitest-docker
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Run unit-tests
        run: make tests_run
      
      - name: Run coverage
        run: make coverage
