name: Tests

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  unit-test:
    runs-on: ubuntu-20.04
    container:
      image: epitechcontent/epitest-docker
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Run unit-tests
        run: make tests_run > unit_tests_output.txt
      
      - name: Run coverage
        run: make coverage > coverage_output.txt
      
      - name: Upload unit tests artifacts
        uses: actions/upload-artifact@v3
        with:
          name: unit_tests_outputs
          path: unit_tests_output.txt
      
      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage_outputs
          path: coverage_output.txt
